language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - LARAVEL_ENV=development php -S localhost:4443 -t ./public/ &
  - mysql -u root -e 'create database IF NOT EXISTS gommunity;'

script: phantomjs --webdriver=4444