language: php
php:
  - "5.5"
  - "5.4"
before_script:
  - LARAVEL_ENV=development php -S localhost:4443 -t ./public/ &
  - phantomjs --webdriver=4444 &
  - mysql -u root -e 'create database IF NOT EXISTS gommunity;'

script: php vendor/codeception/codeception/codecept run